### PR TITLE
Add ESLint, remove dead code

### PR DESCRIPTION
**Pull request by XhmikosR**
Non-whitespace diff: https://github.com/sagarkarira/coronavirus-tracker-cli/pull/30/files?w=1

### CODE REVIEW

**Comment by XhmikosR** [comment]
@sagarkarira BTW if you'd like to add GitHub Actions CI support let me know and I'll make a new patch later :)

**Comment by sagarkarira** [comment]
Sorry, @XhmikosR I merged two PR today which had a lot of changes. Do you want to look at this again?

**Comment by XhmikosR** [comment]
@sagarkarira should be OK now. Personally I prefer using xo for linting, so let me know if you want me to switch to that in another PR.

**Comment by sagarkarira** [comment]
Thanks for contributing @XhmikosR  ❤️ .

**Comment by XhmikosR** [comment]
Where's yargonaut used @sagarkarira ?

**Comment by sagarkarira** [comment]
It adds color to yargs commands. You just need to declare it top of yargs and it does this automatically. Check [here](https://www.npmjs.com/package/yargonaut)

**Comment by XhmikosR** [comment]
Oh, OK. Then you missed the package-lock.json. If you fetch the latest master and do `npm i` you will see the lock file is modified. After you commit it ping me so that I proceed with the rest of the PRs :)

**Comment by sagarkarira** [comment]
You are right. I pushed it.

**Comment by XhmikosR** [comment]
For what is worth, with #33 you'd see it before merging https://github.com/XhmikosR/coronavirus-tracker-cli/runs/522090935#step:6:6

**Pull request merged**
