### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by XhmikosR**
Needs tests or ESLint so I'll rebase it after #30 :)

### CODE REVIEW

**Comment by XhmikosR** [comment]
@sagarkarira the package-lock.json was not right in master either. The last patch I have here fixes it. Preview: https://github.com/XhmikosR/coronavirus-tracker-cli/runs/522111636

Note that this will run from the next PR for security reasons.

**Comment by sagarkarira** [comment]
Strange. I removed all node_modules and installed again. Still getting old
package-lock.json.

**Comment by XhmikosR** [comment]
This fixes it for sure as you can see, since `npm ci` would error out otherwise :)

**Comment by sagarkarira** [comment]
Great, I am merging this.

**Pull request merged**
